# Generated by Django 6.0.2 on 2026-02-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicejob',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On the Way', 'On the Way'), ('Arrived', 'Arrived'), ('Pending Approval', 'Pending Approval'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
